const express = require('express');
const router = express.Router();
const axios = require('axios');
const pool = require('../config/database');

// Configure your Sarvam API key here or via env variable
const SARVAM_API_KEY = process.env.SARVAM_API_KEY || 'sk_1ht1ormx_SfNT1gi4PRWNePVKl6Kl6nWD';
const SARVAM_API_URL = 'https://api.sarvam.ai/v1/chat/completions';

// 1. Generate Job Description
router.post('/generate-jd', async (req, res) => {
    try {
        const {
            job_title,
            job_domain,
            min_experience,
            max_experience,
            job_type,
            location,
            skills,
            min_salary,
            max_salary,
            show_salary_to_candidate
        } = req.body;

        const isInternship = job_type === 'Internship' || job_type === 'internship';
        const salaryLabel = isInternship ? 'Stipend (INR/month):' : 'CTC:';

        let salaryText = '';
        if (min_salary && max_salary) {
            salaryText = `INR ${Number(min_salary).toLocaleString('en-IN')} - INR ${Number(max_salary).toLocaleString('en-IN')}`;
        } else if (min_salary) {
            salaryText = `INR ${Number(min_salary).toLocaleString('en-IN')}`;
        } else {
            salaryText = 'Best in Industry';
        }

        const compensationRequirement = show_salary_to_candidate
            ? `- **Compensation:** ${salaryLabel} ${salaryText}`
            : '';

        const compensationHtmlTemplate = show_salary_to_candidate
            ? `\n<h3>Compensation</h3>\n<p>...</p>\n`
            : '';

        const prompt = `You are an expert technical recruiter and HR professional. 
Generate a comprehensive, professional, and engaging Job Description for the following role:

- **Job Title:** ${job_title || 'N/A'}
- **Department/Domain:** ${job_domain || 'N/A'}
- **Experience Required:** ${min_experience || '0'} to ${max_experience || '0'} years
- **Employment Type:** ${job_type || 'Full-time'}
- **Location:** ${Array.isArray(location) ? location.join(', ') : (location || 'N/A')}
- **Key Skills:** ${Array.isArray(skills) ? skills.join(', ') : (skills || 'N/A')}
- **Education Requirement:** ${req.body.education || 'BE/B Tech/BCA/MCA/Equivalent'}
${compensationRequirement}

Your output MUST be well-structured and formatted using HTML elements so it can be directly inserted into a rich text editor.
Do NOT include markdown formatting like \`\`\`html. Just return the raw HTML string.
CRITICAL FORMATTING RULES:
- Do NOT generate an "About Our Company", "About Us", or "Why Join Us" section. Stick ONLY to the headers provided below.
- Do NOT add empty paragraph tags (<p><br></p>) or line breaks (<br>) between list items or paragraphs.
- Keep the content within each section compact. Spacing should only exist between different section headings (e.g., between </ul> and the next <h3>), but NOT within the content of a section itself.
- Do NOT add <br> or empty lines inside <ul> or <ol> lists.
Please use the following structure and use appropriate HTML tags (<h3>, <p>, <ul>, <li>, <strong>, etc.):

<h3>Position Overview</h3>
<p>...</p>

<h3>Technical Skills</h3>
<ul><li>...</li></ul>

<h3>Roles and Responsibilities</h3>
<ul><li>...</li></ul>

<h3>Preferred Qualifications</h3>
<ul><li>...</li></ul>

<h3>Education</h3>
<p>...</p>

<h3>Experience</h3>
<p>...</p>
${compensationHtmlTemplate}
<h3>Location</h3>
<p>...</p>`;

        const response = await axios.post(
            SARVAM_API_URL,
            {
                model: "sarvam-30b", // Update to the exact Sarvam model name if different
                messages: [{ role: "user", content: prompt }],
                temperature: 0.7,
                max_tokens: 4000
            },
            {
                headers: {
                    'Content-Type': 'application/json',
                    'Authorization': `Bearer ${SARVAM_API_KEY}`
                }
            }
        );

        let htmlContent = response.data?.choices?.[0]?.message?.content || response.data?.choices?.[0]?.message?.reasoning_content || '';

        // Clean up potential markdown formatting if the LLM output it by mistake
        htmlContent = htmlContent.replaceAll('```html', '').replaceAll('```', '').trim();

        // Aggressively remove empty line breaks and excessive tag spacing generated by the LLM
        htmlContent = htmlContent
            .replace(/<p><br\/?><\/p>/gi, '')
            .replace(/<br\s*\/?>/gi, '')
            .replace(/<\/li>\s*<li>/gi, '</li><li>') // Strip whitespace between list items
            .replace(/<\/p>\s*<p>/gi, '</p><p>');

        res.json({ success: true, description: htmlContent });
    } catch (error) {
        console.error('Error in /generate-jd:', error?.response?.data || error.message);
        res.status(500).json({ success: false, error: 'Failed to generate job description', details: error?.response?.data || error.message });
    }
});

// 2. Chat with FluidJobs AI Mentor
router.post('/chat', async (req, res) => {
    try {
        const { messages } = req.body;

        if (!messages || !Array.isArray(messages)) {
            return res.status(400).json({ success: false, error: 'Messages array is required' });
        }

        const systemPrompt = `You are the FluidJobs AI Mentor, a helpful, professional, and knowledgeable AI assistant built directly into the FluidJobs recruitment platform.

Your primary goal is to help recruiters, HR professionals, and admins use the FluidJobs platform effectively. You function as a built-in product mentor.

*** KNOWLEDGE BASE & WORKFLOWS ***
- **Creating a Job Opening:** Users can create jobs via the "Create Job" button. They will fill in details like Job Title, Domain, Location, Experience, Salary. They can use the AI Job Description Generator to write the JD. They must also define a Hiring Pipeline (stages) and Assign the Hiring Team.
- **Editing Job Openings:** Go to the Job Dashboard, click "Job Settings" to edit details, manage images, change status (Pause/Close).
- **Managing Candidates:** Use the "Candidate Tracker" to view all applicants. You can filter by job, status, or search.
- **Hiring Pipeline Stages:** Candidates move through stages like Applied, Screening, Interview, Offered, Hired. Users can move them by selecting the candidate and clicking 'Move to Next Stage' or using the action menus.
- **Assignment & Approvals:** Recruiters can self-assign candidates. Edits to active jobs by Recruiters require Admin approval.
- **Restrictions:** Candidates can be restricted (blocked) from applying to future jobs if they violate terms or fail background checks. Use the Candidate Restrictions tab.
- **Recruiter Accounts:** Team management is done in the Admin Dashboard under "Accounts" or "Team".

*** STRICT SECURITY BOUNDARIES ***
You MUST STRICTLY REFUSE to answer any questions about or requests for:
- Passwords
- API keys
- Credentials
- Internal security configurations
- User private data (emails, phone numbers, PII)
- System permissions architecture
- Database access or schema details
- Admin secrets or tokens

If asked about any of the restricted topics above, or anything outside of platform usage and workflows, you MUST reply with EXACTLY:
"I can only assist with platform usage and workflows."

*** COMMUNICATION STYLE ***
- Provide clear, step-by-step instructions.
- Use short and easy-to-understand explanations.
- Focus on helping users complete tasks on the FluidJobs platform.
- Avoid unnecessary long responses.
- Maintain a professional, friendly assistant tone.
- Use simple formatting (bullet points, bold text).`;

        const apiMessages = [
            { role: "system", content: systemPrompt },
            ...messages.map(m => ({ role: m.role, content: m.content }))
        ];

        const response = await axios.post(
            SARVAM_API_URL,
            {
                model: "sarvam-30b",
                messages: apiMessages,
                temperature: 0.3,
                max_tokens: 4000
            },
            {
                headers: {
                    'Content-Type': 'application/json',
                    'Authorization': `Bearer ${SARVAM_API_KEY}`
                }
            }
        );
        let reply;
        if (response.data && response.data.choices && response.data.choices.length > 0) {
            reply = response.data.choices[0].message?.content || response.data.choices[0].message?.reasoning_content;
        }

        if (!reply) {
            // Check if Sarvam sent an error object inside a 200 OK response
            if (response.data && response.data.error) {
                console.error("Sarvam API internal error:", response.data.error);
                reply = `AI Service Error: ${JSON.stringify(response.data.error)}`;
            } else {
                console.warn("Sarvam API returned unexpected format:", JSON.stringify(response.data));
                reply = 'I encountered an error processing your request.';
            }
        }
        const lowerReply = reply.toLowerCase();
        if (lowerReply.includes('password') && lowerReply.includes('database')) {
            return res.json({ success: true, reply: "I can only assist with platform usage and workflows." })
        }

        res.json({ success: true, reply });
    } catch (error) {
        console.error('Error in /chat:', error?.response?.data || error.message);
        res.status(500).json({ success: false, error: 'Failed to communicate with AI Mentor', details: error?.response?.data || error.message });
    }
});

// 3. Score Candidate Resume
router.post('/score-candidate/:candidateId', async (req, res) => {
    try {
        const { candidateId } = req.params;

        // Fetch candidate data
        const candidateResult = await pool.query(
            "SELECT * FROM candidates WHERE candidate_id = $1",
            [candidateId]
        );

        if (candidateResult.rows.length === 0) {
            return res.status(404).json({ success: false, error: 'Candidate not found' });
        }
        const candidate = candidateResult.rows[0];

        // Format candidate info into a prompt
        const prompt = `You are an expert AI recruiter. Evaluate this candidate and assign a score out of 100 based on their profile.
Candidate Name: ${candidate.full_name}
Experience: ${candidate.experience_years || 0} years
Current Company: ${candidate.current_company || 'Not provided'}
Notice Period: ${candidate.notice_period || 'Not provided'}
Expected CTC: ${candidate.expected_ctc || 'Not provided'}

Reply with ONLY a JSON object in this exact format, with no markdown:
{"score": 85, "reasoning": "Brief explanation..."}`;

        const response = await axios.post(
            SARVAM_API_URL,
            {
                model: "sarvam-30b",
                messages: [{ role: "user", content: prompt }],
                temperature: 0.1,
                max_tokens: 4000
            },
            {
                headers: {
                    'Content-Type': 'application/json',
                    'Authorization': `Bearer ${SARVAM_API_KEY}`
                }
            }
        );

        let reply = response.data?.choices?.[0]?.message?.content || response.data?.choices?.[0]?.message?.reasoning_content;
        if (!reply) {
            return res.status(500).json({ success: false, error: 'Failed to generate score.' });
        }

        // Clean up markdown in case the model returns it
        reply = reply.replace(/\`\`\`json/g, '').replace(/\`\`\`/g, '').trim();

        let scoreData;
        try {
            scoreData = JSON.parse(reply);
        } catch (e) {
            // Fallback parsing if JSON fails
            const scoreMatch = reply.match(/"score"\s*:\s*(\d+)/) || reply.match(/score.*?(\d+)/i);
            const score = scoreMatch ? parseInt(scoreMatch[1]) : 0;
            scoreData = { score, reasoning: "Parsed from text response" };
        }

        const finalScore = scoreData.score || 0;

        // Save to ai_data table (creating record if missing)
        await pool.query(`
            INSERT INTO ai_data (candidate_id, resume_score, updated_at)
            VALUES ($1, $2, CURRENT_TIMESTAMP)
            ON CONFLICT (candidate_id) 
            DO UPDATE SET 
                resume_score = $2,
                updated_at = CURRENT_TIMESTAMP
        `, [candidateId, finalScore]);

        res.json({ success: true, score: finalScore, reasoning: scoreData.reasoning });

    } catch (error) {
        console.error('Error in /score-candidate:', error?.response?.data || error.message);
        res.status(500).json({ success: false, error: 'Failed to score candidate', details: error?.response?.data || error.message });
    }
});

module.exports = router;
